# Generated by Django 2.0.2 on 2018-04-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_osuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osuser',
            name='userid',
        ),
    ]
